apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-env
spec:
  containers:
    - name: demo
      image: alpine:3.19
      imagePullPolicy: IfNotPresent
      command: ["sleep", "3600"]
      env:
        - name: THEME
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: THEME
