apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENV_NAME: "Biztonsági Bemutató"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
        - name: flask-app
          image: my-flask-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENV_NAME
            - name: SECRET_DATA
              valueFrom:
                secretKeyRef:
                  name: db-pass
                  key: SECRET_DATA
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
